### ISSUE TITLE
RestrictPitch

### ISSUE THREAD

**Issue by mjcumming** [rocheparadox/Kalman-Filter-Python-for-mpu6050#1]
Hi,

Would you explain how the RestricPitch flag works?

**Comment by rocheparadox** [comment]
Yeah sure. You can contact me through my mail Id rocheinside@gmail.com 
You can go through this document for reference  https://www.nxp.com/files-static/sensors/doc/app_note/AN3461.pdf

**Comment by mjcumming** [comment]
Thank you for the link to the article - I can't claim to understand all the math :) but I understand the need for the restrict pitch setting. Thank you!
