### ISSUE TITLE
Typo error in AngleOmeter:

### ISSUE THREAD

**Issue by wojciechben** [rocheparadox/Kalman-Filter-Python-for-mpu6050#2]
Starting at line 153 is:
#angle = (rate of change of angle) * change in time
	    gyroXAngle = gyroXRate * dt
	    gyroYAngle = gyroYAngle * dt

Shouldn't it be gyroYRate in second line of code?
I did not see the difference when playing with code/real device but...

**Comment by rocheparadox** [comment]
Yeah, That is a stupid typo mistake. The reason, you did not find any changes in output by correcting it is because the same does not have any impact on final output angles.
