### ISSUE TITLE
Only get x Data

### ISSUE THREAD

**Issue by Tronje-the-Falconer** [rocheparadox/Kalman-Filter-Python-for-mpu6050#4]
Hello I tryied your Kalman-Filter with your AngleOMeter. It works very well, but I only get X-Data. The Y-Data is always 0.
When I change RestrictPitch to False, i get only Y-Data.
So I think there is an else: too much in Line 139. When i comment it out it works fine on both Axis.

Best Regards

**Comment by rocheparadox** [comment]
Yeah. My bad. I changed it locally. I have to cross check the math. I will commit it then.
Thanks :)
